//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasXCobrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balances
    {
        public int IdCliente { get; set; }
        public System.DateTime FechaCorte { get; set; }
        public System.DateTime AntiguedadPromedioSaldos { get; set; }
        public decimal Monto { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
