//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasXCobrar
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBCuentasxCobrarEntities : DbContext
    {
        public DBCuentasxCobrarEntities()
            : base("name=DBCuentasxCobrarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asientos_Contables> Asientos_Contables { get; set; }
        public virtual DbSet<Balances> Balances { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<TipoDocumentos> TipoDocumentos { get; set; }
        public virtual DbSet<TipoMovimientos> TipoMovimientos { get; set; }
        public virtual DbSet<Transacciones> Transacciones { get; set; }
    }
}
