//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasXCobrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacciones
    {
        public int IdTrans { get; set; }
        public int IdMovimiento { get; set; }
        public int IdDoc { get; set; }
        public int IdCliente { get; set; }
        public int NumeroDocumento { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Monto { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual TipoDocumentos TipoDocumentos { get; set; }
        public virtual TipoMovimientos TipoMovimientos { get; set; }
    }
}
